name: "Install a binary from GitHub releases"
description: "Install binaries from GitHub releases"
author: "Lee Briggs"
inputs:
  repo:
    description: "GitHub repo where binary is located"
    required: true
  binary_name:
    description: "Name of binary to install"
    required: true
  tag:
    description: "tag containing binary to install"
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
